The commit fixes corner case if in upstream PR is deleted file.
The downstream file is properly deleted by `os.unlink` code, it is still present.
But the code that is now in Exception fixes the problem,
because upstream file is not present and 'os.readlink(src_path_content)'
failed with traceback FileNotFoundError.

The traceback is mentioned below in the commit message.

See real error:
rh_cwt.main.distgit - DEBUG: unlink nginx-124/results/test/run-openshift
Traceback (most recent call last):
  File "/usr/local/bin/rhcwt", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/phracek/.local/lib/python3.12/site-packages/rh_cwt/cli.py", line 169, in run
    cli.run()
  File "/home/phracek/.local/lib/python3.12/site-packages/rh_cwt/cli.py", line 163, in run
    run_function()
  File "/home/phracek/.local/lib/python3.12/site-packages/rh_cwt/main.py", line 369, in dist_git_merge_changes
    super(RhelImageRebuilder, self).dist_git_merge_changes(rebase)
  File "/home/phracek/.local/lib/python3.12/site-packages/container_workflow_tool/main.py", line 578, in dist_git_merge_changes
    self.distgit.dist_git_merge_changes(images, rebase)
  File "/home/phracek/.local/lib/python3.12/site-packages/container_workflow_tool/distgit.py", line 99, in dist_git_merge_changes
    self.pull_upstream(component, path, url, repo, ups_name, commands)
  File "/home/phracek/.local/lib/python3.12/site-packages/container_workflow_tool/git_operations.py", line 259, in pull_upstream
    self.sync_handler.handle_dangling_symlinks(cp_path, component)
  File "/home/phracek/.local/lib/python3.12/site-packages/container_workflow_tool/sync.py", line 101, in handle_dangling_symlinks
    os.readlink(src_path_content))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'upstreams/nginx/1.24/results/test/run-openshift'

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>